// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2YyCSfXSkFxJU-2M-0Ho0SE9LF_hFb98',
    appId: '1:36939145380:web:3e495117a99827b8f94631',
    messagingSenderId: '36939145380',
    projectId: 'doctorbooking2023',
    authDomain: 'doctorbooking2023.firebaseapp.com',
    storageBucket: 'doctorbooking2023.appspot.com',
    measurementId: 'G-RTY1K1R94B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALLl5VGMBBgLiymW2p3wtVA4qe9K0WVmo',
    appId: '1:36939145380:android:c56d0d8a6f8a2104f94631',
    messagingSenderId: '36939145380',
    projectId: 'doctorbooking2023',
    storageBucket: 'doctorbooking2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGR2LVqmvDGzBxquq91gAWUKg-QhuqpXE',
    appId: '1:36939145380:ios:b75eb209fb8b256cf94631',
    messagingSenderId: '36939145380',
    projectId: 'doctorbooking2023',
    storageBucket: 'doctorbooking2023.appspot.com',
    iosClientId: '36939145380-b6s70k2ptv3dvdkb2c5r69f54iffm17k.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorBookingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGR2LVqmvDGzBxquq91gAWUKg-QhuqpXE',
    appId: '1:36939145380:ios:fde9e8da79c2c97af94631',
    messagingSenderId: '36939145380',
    projectId: 'doctorbooking2023',
    storageBucket: 'doctorbooking2023.appspot.com',
    iosClientId: '36939145380-d7trvvk7en5uibnrnh126qge8qi85sq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorBookingFlutter.RunnerTests',
  );
}
